=== DavidLawrence25/board-bee/schema/v0_0/board.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema#",
  "title": "Board",
  "description": "...",
  "type": "object",
  "properties": {
    "__metadata__": {
      "$ref": "./metadata.json"
    },
    "tasks": {
      "description": "An array of Task objects",
      "type": "array",
      "items": {
        "$ref": "./task.json"
      }
    },
    "events": {
      "description": "An array of Event objects",
      "type": "array",
      "items": {
        "$ref": "./event.json"
      }
    },
    "task_generators": {
      "description": "An array of TaskGenerator objects",
      "type": "array"
    },
    "event_generators": {
      "description": "An array of EventGenerator objects",
      "type": "array"
    }
  },
  "required": [
    "__metadata__",
    "tasks",
    "events",
    "task_generators",
    "event_generators"
  ],
  "additionalProperties": false
}

=== DavidLawrence25/board-bee/sample.json
{
  "__metadata__": {
    "board_bee_version": 0.0,
    "name": "School",
    "labels": {},
    "flags": []
  },
  "tasks": [],
  "events": [],
  "task_generators": [],
  "event_generators": [
    "https://www.kanzaki.com/docs/ical/rrule.html",
    {
      "name": "Thanksgiving",
      "start_dates": {
        "start": "1941-11-27 00:00:00",
        "end": "1941-11-27 23:59:59"
      },
      "recurrence_rule": {
        "frequency_mode": "yearly",
        "filters": {
          "months": [11],
          "weekdays": ["thursday"],
          "set_pos": [4]
        }
      }
    },
    {
      "name": "Election Day",
      "start_dates": {
        "start": "1996-11-05 00:00:00",
        "end": "1996-11-05 23:59:59"
      },
      "recurrence_rule": {
        "frequency_mode": "yearly",
        "interval": 4,
        "filters": {
          "months": [11],
          "weekdays": ["tuesday"],
          "month_days": [2, 3, 4, 5, 6, 7, 8]
        }
      }
    }
  ]
}
